lynxkite/lynxkite

app/com/lynxanalytics/biggraph/graph_operations/Conversions.scala
Easy to miss typo! The NUS tutorial manages to trigger this by using a numeric edge attribute as a label. For parallel edges the attributes get added to a Set, and then this happens.
=> Cast Set to Set, not Seq

app/com/lynxanalytics/biggraph/controllers/OperationParams.scala, app/com/lynxanalytics/biggraph/frontend_operations/EdgeAttributeOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/VertexAttributeOperations.scala, web/app/help/directory-ui/directories.asciidoc, web/app/help/internals/index.asciidoc, web/app/scripts/report-error.js, web/app/scripts/splash/splash.html, web/app/scripts/util/user-menu.html, web/app/scripts/workspace/workspace-drawing-board.html, web/app/styles/user-menu.css
Some minor things noticed in RC1.
The link in the user menu:
The rest of the links are not visible, but work. 😄 
Converting Double attributes to Double being an error is an acute problem for migration. But it could also come up where the list to convert is a parametric parameter.
=> Last fixes before release

test/com/lynxanalytics/biggraph/frontend_operations/SegmentByGeographicalProximityOperationTest.scala
I think making the IDs positive upended this test. With this change all backend tests pass! (I wish I had checked this earlier...)
=> Fix geographic proximity test

app/com/lynxanalytics/biggraph/frontend_operations/Operations.scala, test/com/lynxanalytics/biggraph/frontend_operations/ComputeInPythonTest.scala
Fixes #42. `\W` is a non-word character, but it doesn't match for the start of the string. `\b` is word boundary and it's the perfect thing for this.
=> Fix type inference regex

sphynx/.gitignore, sphynx/go.mod, sphynx/go.sum, sphynx/lynxkite-sphynx/types.go, sphynx/proto_compile.sh, sphynx/sphynx_common.sh, sphynx/sphynx_compile.sh
The same thing could actually also work with the old `protoc-gen-go`. But it looks like they just happen to be changing the whole thing, so this is also an upgrade.
[`github.com/golang/protobuf`](https://github.com/golang/protobuf) is the old one. [`google.golang.org/protobuf`](https://pkg.go.dev/mod/google.golang.org/protobuf) is the new one.
In the old thing the GRPC generator was a plugin of the Go `protoc` plugin. In the new thing it is a separate `protoc` plugin. (See https://github.com/grpc/grpc-go/pull/3453.)
The API is largely unchanged, but now requires this UnimplementedServer thing. (See https://github.com/grpc/grpc-go/pull/3657.)
We still depend on the old library in `go.mod`. This is because the generated code still imports the old library. Why does the new generator generate …
=> Use protoc-gen-go-grpc

web/app/scripts/workspace/workspace-drawing-board.html, web/app/styles/workspace.css
Fixes #15. I didn't move the 95% opacity to the CSS because it doesn't make any visual difference, but it may have a slight performance impact. Not sure why we had it.
=> Make links in comments clickable

.eslintrc.yaml, web/app/scripts/workspace/operation-selector.html
Fixes #52. You can't see more than 10-20 on the screen anyway. The list can be scrolled. But if Google is okay with displaying 10 results on a page maybe it's okay for us to not show them all either.
It's way faster on my laptop this way. Some stuff took 10+ seconds, but now everything is instantaneous.
=> Make search box fast

sphynx/proto_compile.sh
**Description**
Building LynxKite with `make` doesn't work on a Mac, because the Linux version version of `protobuf` and `protoc-gen-grpc-java` are downloaded by default in `sphynx/proto_compile.sh`. In this pull request I'm addressing this by checking the operating system and downloading the correct version (either `osx` or `linux`).
=> Fix `proto_compile.sh` on Mac

app/com/lynxanalytics/biggraph/frontend_operations/ExportOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/ImportOperations.scala, build.sbt, dependency-licenses/scala.md, test/com/lynxanalytics/biggraph/frontend_operations/ExportBoxTest.scala, web/app/help/operations/export-to-avro.asciidoc, web/app/help/operations/import-avro.asciidoc, web/app/help/operations/index.asciidoc
Added support for importing and exporting AVRO files. 
Since the release of Spark 2.4, Spark SQL has built-in support for reading and writing Apache Avro data ([see here](https://spark.apache.org/docs/2.4.0/sql-data-sources-avro.html)). It was therefore relatively straightforward to add this functionality to LynxKite.
=> Import & Export AVRO files

python/remote_api/src/lynx/kite.py, python/remote_api/tests/test_sql_shorthand.py
**Description**
Added state properties for easily accessing `vertices`, `edges`, `graph_attributes`,  `edge_attributes` and `segmentations` in the Python Remote API. 
You can now do things such as:
```python
g = lk.createExampleGraph()
g.vertices
g.edges
g.edge_attributes
g.graph_attributes
g2 = g.findConnectedComponents(name="example")
g.segmentations["example"]
```
=> Added state.vertices, state.edges, etc.

web/app/styles/operation-selector.css, web/app/styles/table-state-view.css
I'm not sure many people noticed that the icons were slightly off-center. But the whole toolbar scrolling away in the table output popups always felt embarrassing in demos. Looks like the rule to make it scroll right was kind of there, just on the wrong element. That was probably the right element at some point. 😅
=> Small CSS fixes

CHANGELOG.md, web/app/scripts/project/graph-view.js
Reported by Péter Vakhal. (Thanks!) The edge weights in the example graph are integers, so there's no problem there. The `double` and `string` values in DynamicValue are the same. But with non-integers the two can be different and then the lookup in the colormap does not find the entry.
=> Fix edge coloring with long fractional numbers

app/com/lynxanalytics/biggraph/frontend_operations/ExportOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/ImportOperations.scala, app/com/lynxanalytics/biggraph/spark_util/BigGraphSparkContext.scala, build.sbt, test/com/lynxanalytics/biggraph/frontend_operations/ExportBoxTest.scala, web/app/help/operations/export-to-delta.asciidoc, web/app/help/operations/import-delta.asciidoc, web/app/help/operations/index.asciidoc
**Description**
In this pull request I have added support for reading and writing to Delta Lake in LynxKite. "Delta Lake is an open-source storage layer that brings ACID transactions to to Apache Spark and big data workloads." \[1\] 
I used Delta version `0.6.1`, since versions >= `0.7.x` require Spark 3.0. 
\[1\]: https://docs.delta.io/latest/index.html
=> Add support for Delta format

app/com/lynxanalytics/biggraph/frontend_operations/ExportOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/ImportOperations.scala, app/com/lynxanalytics/biggraph/graph_operations/ExportToNeo4j.scala, app/com/lynxanalytics/biggraph/graph_util/Scripting.scala, build.sbt, test/com/lynxanalytics/biggraph/frontend_operations/Neo4jExportImportTest.scala, web/app/help/operations/export-edge-attributes-to-neo4j.asciidoc, web/app/help/operations/export-graph-to-neo4j.asciidoc, web/app/help/operations/export-vertex-attributes-to-neo4j.asciidoc, web/app/help/operations/index.asciidoc
This is part 1: exporting attributes for existing nodes.
There's an option to set `node.keys` and let them build the query. But if I use that, the label is a must. If I write the same query manually, I can leave it off. (http://5.9.211.195:8000/neo4j-spark-docs/1.0.0/writing.html#bookmark-write-node)
Open tasks:
=> Neo4j export

conf/logger-docker.xml
Resolves #126. The logs are accessible from `/logs` in a browser.
=> Still log to rolling log files in Docker

build.sbt, dependency-licenses/scala.md, sphynx/go.mod, sphynx/go.sum, sphynx/lynxkite-sphynx/entity_cache.go, sphynx/lynxkite-sphynx/entity_io.go, sphynx/lynxkite-sphynx/main.go, sphynx/lynxkite-sphynx/networkit_community_detection.go, sphynx/lynxkite-sphynx/networkit_test.go, sphynx/lynxkite-sphynx/operations.go, sphynx/lynxkite-sphynx/sphynxdisk.go, sphynx/lynxkite-sphynx/strip_duplicate_edges_from_bundle.go, sphynx/lynxkite-sphynx/types.go, sphynx/lynxkite-sphynx/unordered_disk_io.go, sphynx/lynxkite-sphynx/vertex_attribute_filter.go, sphynx/lynxkite-sphynx/vertex_set_intersection.go
The idea (from @xandrew-lynx) being that `MappingToOrdered` takes up a lot of memory. The tests seem to be passing locally. I haven't measured the impact on memory use yet. I also haven't thought backward compatibility entirely through.
=> Ditch ordered mapping

web/app/scripts/splash/entry-selector.js, web/app/styles/operation-selector.css, web/app/styles/workspace.css
Fixes #153. Fixes #154.
The flickering was caused by the CSS transition of the `transform` on box hover. If you make the transition longer (I used 1000 seconds) you can inspect where the category selector goes off to. It's somewhere off-screen. Interestingly the magnifying glass icon stays in place.
I'm not sure how this selector was positioned in the first place. It had a `float: left` property. But it's on the right? Anyway, I changed it to `position: absolute; right: 0;` which makes more sense and also works even during the transition.
As I was testing to make sure this works with all sorts of window sizes, I notice that a long workspace name subtly breaks a few things and looks ugly. I've changed it so this never happens. We rather truncate the workspace name with a "..." at the end. …
=> Small UI fixes

web/app/scripts/splash/entry-selector.js
Sorry, when I fixed #154 I fixed it for folders that have a space in them but broke it for folders with other special characters. Maybe this fix will do it.
=> Try to fix "@" and " " in the folder name at the same time

CHANGELOG.md, sphynx/lynxkite-sphynx/unordered_disk_io.go
In LynxKite 4.2.1 I've discovered an attribute corruption bug. I've seen all values or everything except the first value disappear from an attribute. It's happening somewhat randomly, but not on small data. In my repro I'm importing a CSV with 600,000 lines, using it as a graph, and out of the 5 attribute there is a good chance that one or more will be affected.
I've tracked it to `PulledOverVertexAttribute`. It gets a good Parquet file as the input and writes out a bad Arrow file (undefined almost everywhere). I've added debug stuff in `PulledOverVertexAttribute` and saw that it sees the input attribute already as mostly undefined.
I've added debug stuff in `unordered_disk_io.go` and here I saw this in `permutation[:10]`: `[0 0 0 419538 1 419539 209908 209909 209910 2]`. That is not a …
=> Fix attribute corruption

app/com/lynxanalytics/biggraph/graph_api/JsonMigration.scala, app/com/lynxanalytics/biggraph/graph_operations/AttributeFilters.scala, app/com/lynxanalytics/biggraph/graph_operations/CollectAttribute.scala, app/com/lynxanalytics/biggraph/graph_operations/RestrictedAttribute.scala, app/com/lynxanalytics/biggraph/graph_operations/SampledView.scala, app/com/lynxanalytics/biggraph/graph_operations/TripletAttributes.scala
Sets are serialized to JSON as arrays in arbitrary order. The arbitrary order changed due to some upgrade in #178. This caused a GUID mismatch when loading operations that have Set parameters. There are not many such operations and they are mostly in visualizations. So I just increased the JSON version. This will create a migration and these operations will have to be recomputed.
I've also changed the JSON output to use sorted arrays so we won't hit this issue again.
=> Compatibility fix for Set parameters

built-ins/draw-ROC-curve, sphynx/python/install-dependencies.sh
Thanks @erbenpeter for the comments in #197. I added the sampling to avoid pushing a million points to the plot. But since it's sampled anyway, we can also make the ROC curve in Python. It's one line with scikit-learn and it properly handles the case where the same score is returned multiple times.
Before/after for random 0/1 scores on a balanced dataset:
=> Use sklearn for ROC curve

CHANGELOG.md, app/com/lynxanalytics/biggraph/controllers/Operation.scala, app/com/lynxanalytics/biggraph/controllers/Workspace.scala, app/com/lynxanalytics/biggraph/frontend_operations/WorkflowOperations.scala, app/com/lynxanalytics/biggraph/graph_api/MetaGraphManager.scala, app/com/lynxanalytics/biggraph/spark_util/BigGraphSparkContext.scala, dependency-licenses/javascript.md
I'm addressing multiple issues here:
- Persistent outputs are slower because they write to disk. It's just a bad default.
- The default LIMIT is annoying and no longer necessary if we don't persist the table. (#151)
- Each SQL box created 6 VertexToEdgeAttribute operations per input vertex attribute. With 100 attributes and 20 SQL boxes this was 12,000 operations on every `setAndGetWorkspace` request. That takes around 3 seconds. That's long enough that you start clicking on more things, creating an increasing backlog of requests. In my test I got 20–30 second response times easily.
For the third issue 4 of the 6 VertexToEdgeAttribute operations were unnecessarily caused by the `defaultTableName` code. That's easy to fix. But the other two are unavoidable if we execute the box.
So I've …
=> Faster workspace execution

app/com/lynxanalytics/biggraph/graph_api/io/EntityIO.scala
Unclosed files may or may not get created. So on some filesystems, like GCS we end up with a missing _SUCCESS file here.
=> Fix filesystem-dependent issue with HybridBundle storage

app/com/lynxanalytics/biggraph/graph_api/SphynxDomain.scala, app/com/lynxanalytics/biggraph/graph_util/HadoopFile.scala
Sorry, I added a call to `createEmpty` in #224 but we don't even have `createEmpty`. This was added on a private repo in October and I forgot to upstream it. This should do some good for the tests...
=> Fix _SUCCESS file creation in SphynxDomain

app/com/lynxanalytics/biggraph/package.scala, tools/call_spark_submit.sh
A bit of [archeology](https://github.com/lynxkite/lynxkite/commit/6424509ff77f3c3a138d9629e21bc3fb582714d2) tells me this `REPOSITORY_MODE` setting served a purpose 8 years ago. Now I'm not even sure `RepositoryDirs` is needed now — we could pick up `KITE_DATA_DIR` when the domain is creating, like how the Sphynx directory settings are picked up. I'm leaving that alone though.
=> Strip slashes from directory settings, simplify code

conda-env.yml, python/remote_api/src/lynx/kite.py, python/remote_api/tests/test_external_computation.py, python/remote_api/tests/test_spark_conversion.py
It's just a few lines, but it makes the Spark–LynxKite integration much more friendly. From Spark to LynxKite:
```python
from pyspark.sql import Row, SparkSession
spark = SparkSession.builder.getOrCreate()
people_df = spark.createDataFrame([
Row(name='Adam', age=23),
Row(name='Eve', age=34),
Row(name='Bob', age=45),
])
relationships_df = spark.createDataFrame([
Row(a='Adam', b='Eve', weight=3),
Row(a='Bob', b='Eve', weight=4),
Row(a='Eve', b='Adam', weight=5),
])
g = lk.from_spark(people_df).useTableAsVertices()
g = lk.useTableAsEdges(
g,
lk.from_spark(relationships_df),
attr='name', src='a', dst='b')
```
From LynxKite to Spark:
```python
t = g.sql('select count(*) from vertices')
t.spark(spark).show()
```
PySpark and LynxKite in this case still use separate Spark applications. But …
=> Python API for interfacing with PySpark DataFrames

docker/run.sh
Fallout from https://github.com/lynxkite/lynxkite/commit/2eced1e7c6b33b0f7ff1602b3fea6c443eb5332f. Sorry.
It's an immediate mitigation, but I still think we should do #251. What's the point of this file?
=> Delete PID files in the right path

app/com/lynxanalytics/biggraph/frontend_operations/ImportOperations.scala, build.sbt, web/app/help/operations/import-delta.asciidoc, web/app/help/operations/import-from-bigquery-raw-table.asciidoc, web/app/help/operations/import-from-bigquery-standard-sql.asciidoc, web/app/help/operations/index.asciidoc
Added feature to import from BigQuery using Google's [spark-bigquery-connector](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/0.25.0).
There are two ways to read from BigQuery: raw table or result of executing BigQuery Standard SQL. Both methods are added as two separate import types.
Ability to export might come later. Also yet to implement the full set of [options / properties](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/0.25.0#properties).
It seemed to take too much time to mock GCP credentials and BigQuery, so no unit tests... 😬
=> Add Import from BigQuery (table or SQL output)

conda-env.yml
=> Force conda to use java11

app/com/lynxanalytics/sandbox/ScalaScript.scala, python/remote_api/tests/test_workspace_builder.py
I think `embeddedDefaults` was supposed to do something similar, but it doesn't work. The classpath has to be set before the interpreter is created. See https://stackoverflow.com/questions/51723400/issues-with-scala-scriptengine-inside-spark-submit-application.
=> Add fat jar to Scala interpreter classpath

web/app/styles/workspace.css
I'm not sure when this happened — I just noticed it on try.lynxkite.com. I don't think we have changed this recently, so maybe it's a change in Chrome?
|before fix|after fix|
|---|---|
|<img width="507" alt="image" src="https://user-images.githubusercontent.com/1268018/189652923-d81012d9-babb-4594-a624-af1896ce625b.png">|<img width="501" alt="image" src="https://user-images.githubusercontent.com/1268018/189653039-911cf280-13e8-47f0-84a8-5742666369c8.png">|
=> Fix paragraphs overlapping in comments

app/com/lynxanalytics/biggraph/frontend_operations/VisualizationOperations.scala, test/com/lynxanalytics/biggraph/frontend_operations/PlotTest.scala
Like if LynxKite is served as `https://demo.lynxkite.com/user/.../lk/`, then we can't redirect to `/downloadCSV`. But `downloadCSV` works, because the frontend is served from the LynxKite root.
=> Fix custom plots when served with a prefix

python/remote_api/src/lynx/kite.py
This unclosed block was causing the API docs to fail to get generated.
=> Fix Python docs

conf/application.conf
This was creating a file called `RUNNING_PID`. I'm on a crusade against PID files. The port (2200) is a perfectly good protection against accidentally running multiple LynxKites.
=> Disable Play Framework pidfile

app/com/lynxanalytics/biggraph/controllers/ParameterHolder.scala, app/com/lynxanalytics/biggraph/scala_sandbox/ScalaScript.scala
Fixes #303. I think the Map would be a fine API too. But to preserve compatibility I'm converting them to the same SimpleGraphEntity, but defined inside ScalaScript.
Unfortunately the backend tests cannot catch this, because they are not running with `spark-submit`. A frontend test could have caught it. I haven't added one here because we're in the process of rewriting them. But I've filed #304 so we don't forget.
=> Do not pass LynxKite objects to ScalaScript

web/app/scripts/workspace/state-view.html
Doesn't look like an element can have multiple IDs like this. I don't know how this ever worked. For me this fixed the Protractor tests.
=> Fix state-toolbar ID for tests

app/com/lynxanalytics/biggraph/controllers/FEBucketers.scala, test/com/lynxanalytics/biggraph/controllers/GraphDrawingControllerTest.scala, web/package.json, web/tests/custom-box.spec.ts, web/tests/filter.spec.ts, web/tests/histogram.spec.ts, web/tests/lynxkite.ts, web/yarn.lock
The histogram test used to include sorting, because the histograms come in unpredictable order. But that's not great for the users either! I've fixed the sorting on the backend.
=> Convert histogram-test.js and filter-test.js

app/com/lynxanalytics/biggraph/LynxKite.scala, python/remote_api/managed_tests/test_start_stop.py, python/remote_api/src/lynx/kite.py, python/remote_api/tests/test_spark_conversion.py
I'll add a test! For now I've tested it manually like this:
```
from pyspark.sql import Row
import lynx.kite
lk = lynx.kite.LynxKite(spark=spark)
df = spark.createDataFrame([Row(name='Adam', age=23), Row(name='Eve', age=34), Row(name='Bob', age=45)])
print(lk.from_spark(df).sql('select * from input where age < 40').df())
```
It's so cool! I'm also going to add the other direction in another PR: LynxKite table to PySpark DataFrame.
=> Use DataFrames from PySpark without writing them to disk

web/app/scripts/app.js, web/tests/lynxkite.ts, web/tests/snapshot.spec.ts
For #238. Playwright's locator gave an error when asked to find `#snapshot-this-is-a-snapshot!` — `!` is not a valid character in an ID. I think browsers can put up with this somehow, but Playwright is surely right. I've changed the ID creator to convert punctuation to `-`.
Otherwise this looks like a meaningful test and a straightforward conversion.
=> Convert snapshot-test.js

resources/built-ins/ask-OpenAI, sphynx/python/derive.py, sphynx/python/llm_pandas_on_graph.py
If I run `python python/llm_pandas_on_graph.py 'the three most popular actors and athletes'` it's pretty good:
````
Change `compute_from_graph(nodes, edges)` to perform the following task:
- the three athletes that have the most fans 
````
````
```python
def compute_from_graph(nodes, edges):
"""the three athletes that have the most fans"""
nodes = nodes[nodes['job'] == 'athlete']
edges = edges[edges['relationship'] == 'fan']
nodes['count'] = edges.groupby('dst').size()
return nodes.nlargest(3, 'count')
```
````
````
Change `compute_from_graph(nodes, edges)` to perform the following task:
- the three most popular actors and athletes 
````
````
```python
def compute_from_graph(nodes, edges):
"""the three most popular actors and athletes"""
nodes = nodes[(nodes['job'] == 'actor') | …
=> Allow specifying custom examples for OpenAI

conda-env.yml, test/com/lynxanalytics/biggraph/frontend_operations/ComputeInPythonTest.scala
Fixes the failure seen on #379:
```
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported.
Convert to a numpy array before indexing instead.
```
=> Fix Python test to be compatible with Pandas 2.0.0

resources/built-ins/ask-OpenAI, sphynx/python/llm_pandas_on_graph.py, web/app/scripts/workspace/op-editor.html, web/app/scripts/workspace/op-editor.js
Sorry, looks like I forgot to update the builtin box in #368.
But if you don't mind, I'll fix two more issues here:
- The custom box description is not rendered as Markdown in the box popup. (As we noticed yesterday.)
- I'll display the table schema and sample column by column.
=> OpenAI box fixes

web/app/index.html
It's hard to reproduce the issue! I'll take a closer look if I hit it next time.
After pushing a new version, if you load everything from cache, that should work fine. If you have a cache miss on index.html, you get the links to the new js/css files. So you will download them too and everything will be fine. The only failure mode I can think of is that you take index.html from the cache, try to load the old js/css but don't have _that_ cached, so you go to the server and get 404s. That doesn't sound like something that we would hit with every update, right?
I've managed to reproduce it this way, and the message in this PR appears. (But you get 303s instead of 404s because we try to redirect to something.)
=> Suggest hard reloading if the JavaScript doesn't load

sphynx/python/util.py, web/app/scripts/workspace/op-editor.js
For #388. _This_ was the real issue in the current case. The distance from the issue to the error message is ridiculous.
To be fair, the Python process only printed this before dying with exit code 134:
```
s2n_init() failed: 335544378 (handshake was cancelled)
Fatal error condition occurred in /home/conda/feedstock_root/build_artifacts/aws-c-io_1679650583274/work/source/s2n/s2n_tls_channel_handler.c:203: 0 && "s2n_init() failed"
Exiting Application
No call stack information available
```
And #388 is not entirely correct. Retrying worked. Sphynx doesn't report the entity as existing because it's not there.
Adding lots of prints narrowed it down to `df.to_pandas()` in our `util.py` which triggers an `import pyarrow.parquet` line in Pandas which triggers `initialize_s3()` in …
=> Fix tables in chroot

app/com/lynxanalytics/biggraph/partitioned_parquet/PartitionedParquet.scala
This is @lacca0's change from another repo. [SPARK-40113](https://github.com/apache/spark/commit/cee30cb4994b178f6999cbbefdcaac21f0d60915) is coming in Spark 3.4.0 but it's already part of the Databricks runtime. I don't think there's any harm in this change. When used with Spark 3.3.0 it may break some pushed filters, but I don't think we rely on those. At least the tests pass!
(Still, let's not merge it before the release.)
=> Update PartitionedParquet code for SPARK-40113

app/com/lynxanalytics/biggraph/scala_sandbox/ScalaScript.scala
For #380. Because SecurityManager has been removed from Java (https://github.com/lynxkite/lynxkite/issues/265) I think making this optional is a reasonable step. For single-user and read-only deployments there is no harm in turning it off. For multi-user environments this will let us explore alternative solutions.
=> Make ScalaScriptSecurityManager optional

CHANGELOG.md, app/com/lynxanalytics/biggraph/frontend_operations/ExportOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/ImportOperations.scala, app/com/lynxanalytics/biggraph/graph_operations/ExportToNeo4j.scala, web/app/help/operations/export-edge-attributes-to-neo4j.asciidoc, web/app/help/operations/export-graph-to-neo4j.asciidoc, web/app/help/operations/export-vertex-attributes-to-neo4j.asciidoc, web/app/help/operations/import-from-neo4j.asciidoc
For https://github.com/lynxkite/lynxkite/discussions/113.
The Neo4j Spark connector [documentation](https://neo4j.com/docs/spark/current/configuration/) says "The driver allows to define the database in the URL [...]". But doesn't specify how! I only see `/db/xxx` in old examples and it's reportedly not working. So let's go with the new parameter.
=> Allow specifying the database for Neo4j import/export

.github/workflows/earthly-test.yml, Earthfile, conda-env.sh, conda-env.yml, conf/logback.xml, test/com/lynxanalytics/biggraph/frontend_operations/LogisticRegressionTest.scala, web/app/scripts/project/graph-view.js, web/package-lock.json, web/package.json, web/playwright.config.ts, web/tests/filter.spec.ts, web/tests/lynxkite.ts
I created CSS color strings in a Python box for the visualization in https://github.com/lynxkite/lynxkite/pull/414. The colors then end up in the legend, making it super long with 100+ nodes. So I added a cutoff. It looks nice:
(Here the color is based on the first three dimensions of the embedding, while the first two are used as for layout.)
=> Skip color legend if long, fix CI issues

CHANGELOG.md, app/com/lynxanalytics/biggraph/controllers/GraphDrawingController.scala, build.sbt, dependency-licenses/scala.md, web/app/scripts/project/load-graph.js
Turns out `KITE_DRAWING_OVERALL` was setting a default visualization size limit, but the frontend was overriding it with a fixed 10,000. 😮‍💨 This change removes the special casing for the 3D view, but I think that's not too bad. You can configure the limit after all!
=> Allow KITE_DRAWING_OVERALL to take effect

Earthfile, app/com/lynxanalytics/biggraph/controllers/Operation.scala, conda-env.sh, conda-env.yml, dependency-licenses/javascript.md, dependency-licenses/scala.md, docker/.gitignore, docker/Dockerfile, python_requirements.txt, python_requirements_cuda.txt, python_requirements_testing.txt, release.sh, sphynx/python/llm_pandas_on_graph.py
Because of the old Java and Spark dependencies (blocked by #265 and #413) Conda refuses to install some new dependencies, like OpenAI 1.x. So I switched to using `pip` for Python dependencies. I don't know if it's `pip`'s fault, but when building the Docker images for 5.4.0 I was surprised to see they are >20GB. To fix that I split `python_requirements.txt` into two. (A bit differently than the CUDA/non-CUDA split was with Conda.)
Now we can build a ~2GB Docker image. But I guess it's better to call this 5.4.1 now.
=> Rearrange Python dependencies

CHANGELOG.md, python/documentation/create_operations_doc.py, python/remote_api/README.md, python/remote_api/pyproject.toml, python/remote_api/src/lynx/kite.py, python/remote_api/src/lynx/operations.py, python/remote_api/tests/test_external_computation.py
Two operations were missing the "Now" functions: `importFromBigQueryRawTable` and `importFromBigQueryStandardSQLResult`. Missing "Now" functions are a problem when working with these sources in Python. Having unnecessary "Now" functions is less problematic. So I changed the code to cover all future operations starting with "import".
I also found a test that was broken in a funny way that still let it pass.
=> Add missing importFooNow functions in Python API
