CHANGELOG.md
A few things were missing. I've also reordered it a bit to put the Python box changes together at the end and added a note about open-sourcing.
=> Tidy up changelog

web/app/scripts/splash/splash.html, web/app/styles/splash.css
No longer needed! Use as you like.
=> Remove EULA

Makefile
We shared this Makefile with some other projects plus we had some plain deprecated parts.
=> Remove unused stuff from Makefile

python/remote_api/lynx_versioning.py, python/remote_api/setup.py
The symlinks are a problem for GitHub Actions and anyway, I think that was overcomplicated.
=> Take version string from environment variable

CHANGELOG.md, docker/Dockerfile, docker/run.sh
Copied from the old repo. (But we can give it a simpler path here!)
There's no system for putting `stage` here yet. I'll figure it out as part of the new release automation.
=> Dockerfile

python/documentation/Introduction.ipynb, python/remote_api/setup.py
I've pushed this to PyPI: https://pypi.org/project/lynxkite-python-api/
=> Update license in Python package

sphynx/python/create_graph_in_python.py, test/com/lynxanalytics/biggraph/frontend_operations/CreateGraphInPythonTest.scala
Missed this in the renaming. Thanks for @xandrew-lynx for reporting.
=> Fix scalar variable in "Create graph in Python"

app/com/lynxanalytics/biggraph/frontend_operations/BuildGraphOperations.scala, test/com/lynxanalytics/biggraph/frontend_operations/ExportImportOperationTest.scala
Also reported by @xandrew-lynx. Thanks!
=> Fix non-String attributes in "Use table as graph"

CHANGELOG.md, web/package.json, web/yarn.lock
Fixes #30. I'll make a release with this fix because it's important for first-time users.
Bootstrap had a similar issue (https://github.com/twbs/bootstrap/issues/30553) which led me to the jQuery issue (https://github.com/jquery/jquery/issues/4665). It's also explained in the [release notes](https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/).
=> Fix guided tour

CHANGELOG.md, web/app/help/operations/copy-edges-to-base-graph.asciidoc, web/app/help/operations/create-edges-from-co-occurrence.asciidoc, web/app/help/operations/sample-edges-from-co-occurrence.asciidoc, web/app/styles/help.css
I thought I would leave the code that used to generate these scalars. It's dead code now, but we want to revive it, right?
=> Remove broken scalars from help

python/documentation/Introduction.ipynb, python/remote_api/src/lynx/kite.py, web/app/admin-manual/architecture/logging.asciidoc, web/app/admin-manual/installation/configuration.asciidoc, web/app/admin-manual/installation/kerberos.asciidoc, web/app/help/operations/copy-edges-to-base-graph.asciidoc, web/app/help/operations/snowball-sample.asciidoc, web/app/help/project-ui/model-details.asciidoc, web/app/help/visualization/index.asciidoc
They sent an email with some typos. It's a subscription service, but I guess the first scan was free. Just hope we don't make any more typos! 😄
=> Fix typos discovered by triplechecker.com

build.sbt, dependency-licenses/scala.md
=> Add some useful GPL dependencies

app/com/lynxanalytics/biggraph/controllers/Project.scala, app/com/lynxanalytics/biggraph/graph_operations/Conversions.scala, app/com/lynxanalytics/biggraph/spark_util/BigGraphSparkContext.scala, build.sbt, github-actions/build/action.yml, project/plugins.sbt
=> Add more Double conversions

CHANGELOG.md, web/app/scripts/project/load-graph.js, web/app/scripts/project/sampled-view-settings.html
=> Add "no edges" edge style

CHANGELOG.md, app/com/lynxanalytics/biggraph/frontend_operations/EdgeAttributeOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/VertexAttributeOperations.scala, test/com/lynxanalytics/biggraph/frontend_operations/ExportImportOperationTest.scala, test/com/lynxanalytics/biggraph/frontend_operations/UseTableTest.scala, web/app/help/operations/use-table-as-edge-attributes.asciidoc, web/app/help/operations/use-table-as-vertex-attributes.asciidoc
Resolves #74. Please double check the values for `if_exists` because we won't be able to change them later. 😰
=> Improvements for "Use table as attributes" boxes

CHANGELOG.md, app/com/lynxanalytics/biggraph/frontend_operations/AttributePropagationOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/Operations.scala, app/com/lynxanalytics/biggraph/frontend_operations/ScalarOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/StructureOperations.scala, web/app/help/operations/glossary.asciidoc
=> Allow disabling suffixes in aggregations

CHANGELOG.md, app/com/lynxanalytics/biggraph/controllers/FEAggregations.scala, app/com/lynxanalytics/biggraph/frontend_operations/Operations.scala, app/com/lynxanalytics/biggraph/graph_operations/Aggregate.scala, test/com/lynxanalytics/biggraph/frontend_operations/AggregateOnNeighborsTest.scala, test/com/lynxanalytics/biggraph/graph_operations/AggregateTest.scala, web/app/help/operations/glossary.asciidoc
Resolves #56. We didn't have very thorough testing for this so I tried to improve that a bit.
=> Aggregation for vectors

sphynx/proto_compile.sh, sphynx/sphynx_common.sh
I ended up building LynxKite on macOS somehow, and had to make these two small changes.
=> Changes for macOS build

python/remote_api/src/lynx/kite.py
Forgot these in #63 , #86, #90, #91. But it's not too late to release a 4.1.0 Python package.
=> Add new import/export operations to Python API

app/com/lynxanalytics/biggraph/controllers/OperationParams.scala, app/com/lynxanalytics/biggraph/frontend_operations/BuildSegmentationOperations.scala, app/com/lynxanalytics/biggraph/frontend_operations/GraphComputationOperations.scala, app/com/lynxanalytics/biggraph/graph_operations/NetworKit.scala, dependency-licenses/scala.md, sphynx/build.sh, sphynx/lynxkite-sphynx/networkit.go, sphynx/lynxkite-sphynx/networkit_community_detection.go, sphynx/lynxkite-sphynx/networkit_compute_attribute.go, sphynx/lynxkite-sphynx/networkit_compute_vector_attribute.go, sphynx/lynxkite-sphynx/networkit_create_graph.go, sphynx/lynxkite-sphynx/networkit_test.go, sphynx/lynxkite-sphynx/operations.go, sphynx/networkit/networkit.swigcxx, sphynx/sphynx_compile.sh, sphynx/test.sh, test/com/lynxanalytics/biggraph/frontend_operations/NetworKitTest.scala, web/app/help/operations/find-communities-with-label-propagation.asciidoc, web/app/help/operations/find-communities-with-the-louvain-method.asciidoc, web/app/help/operations/index.asciidoc, web/app/help/operations/place-vertices-with-edge-lengths.asciidoc
Continuing where #102 left off.
I haven't read up on how PivotMDS works, but on small graphs I got silly layouts. Then I tried it on a larger graph:
(It's a Mocnik random graph. Left is the default LynxKite layout. Right is PivotMDS. 😍 )
=> Layout and community methods from NetworKit

web/app/help/operations/compute-centrality.asciidoc, web/app/scripts/app.js, web/app/scripts/splash/entry-selector.js
Fixes #103. I just hit the same problem from a misconfiguration. The infinite errors were really unhelpful and even killed Chrome Dev Tools. This change allowed me to see the real error.
=> Avoid infinite error loop

conf/kiterc_template, docker/run.sh, web/app/admin-manual/installation/configuration.asciidoc, web/app/admin-manual/installation/configuration/kiterc.asciidoc
A bit of continuation for #110.
=> Some more stuff on config overrides

sphynx/lynxkite-sphynx/networkit_compute_double_edge_attribute.go, test/com/lynxanalytics/biggraph/frontend_operations/NetworKitTest.scala, web/app/help/operations/find-optimal-spanning-tree.asciidoc
For https://github.com/lynxkite/lynxkite/pull/111#discussion_r544229741.
=> Undefined instead of 0 in spanning tree

web/app/scripts/workspace/workspace-drawing-board.js
Fixes #96. Instead of trying to lock everything up for the duration of the upload, it's more of a proper fix. The issue was that the box object does not survive a `setAndGetWorkspace` request. A new box object with the same ID takes its place. But the fix is simple, we just need to look up the right box by ID.
While there I also added a progress indicator for the upload.
=> More feedback, less failing for drag & drop uploads

app/com/lynxanalytics/biggraph/controllers/GraphDrawingController.scala, app/com/lynxanalytics/biggraph/spark_util/RDDUtils.scala
Fixes #97, I hope. I couldn't figure out how to reproduce the issue. Best I can say is that this compiles and LynxKite still starts up after.
=> Better handle attributes in "huge" edge set mode

CHANGELOG.md, web/app/index.html, web/app/scripts/splash/entry-selector.js, web/app/scripts/util/util.js, web/app/scripts/workspace/workspace-wrapper.js, web/basic-annotate.js, web/gulpfile.js, web/package.json, web/test/tests/splash-page-test.js, web/yarn.lock
I tried logging to Firestore first. But I couldn't find a way to do streaming analytics on the data that way. It can export to BigQuery but only with an explicit action. With Firebase Analytics on the other hand I got the data streaming into BigQuery where we can analyze it to our heart's content.
For now it only logs 3 events:
- Every backend request, including the endpoint, the duration, and the error if it failed.
- When a box is added, including the box type. (Custom boxes are not logged.)
- When a vertex or edge count is loaded, the number rounded to two significant digits.
=> Anonymous data collection

sphynx/python/util.py
Fixes #92. Some context: https://stackoverflow.com/questions/808541
I've tried this locally in a chrooted setup and it got me the same behavior as outside of chroot.
=> Properly forward error code in chroot

web/app/scripts/util/top-alerts.js, web/app/scripts/workspace/state-view.js
Fixes #95. Also puts a cap on huge stacks of errors. (Which you can get by repeatedly trying to open an instrument during testing, for example. 😅 )
=> Show errors when opening an instrument

app/com/lynxanalytics/biggraph/serving/JsonServer.scala, conf/kiterc_template, web/app/admin-manual/installation/configuration/kiterc.asciidoc, web/app/scripts/splash/entry-selector.js, web/app/scripts/util/util.js
=> KITE_DATA_COLLECTION setting

app/com/lynxanalytics/biggraph/controllers/ProtoTable.scala
Fixes #119.
| Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/1268018/105199804-793c6300-5b3f-11eb-8e04-f02be0d92344.png)|![image](https://user-images.githubusercontent.com/1268018/105199502-1f3b9d80-5b3f-11eb-9437-3c553881ae5d.png)|
Now it fails before execution.
=> Clear error for empty tables

CHANGELOG.md, dependency-licenses/javascript.md, dependency-licenses/javascript.txt, python/remote_api/src/lynx/operations.py, web/app/scripts/splash/entry-selector.js, web/app/scripts/splash/splash.html, web/app/scripts/util/user-menu.html, web/app/scripts/util/user-menu.js
=> Finishing touches for 4.2.0

web/app/styles/operation-selector.css
I made the selector invisible in #164. Sorry. Not sure how it passed the tests.
=> Make operation selector visible again

CHANGELOG.md
After merging this I'll tag `master` as 4.2.1.
=> Update changelog for 4.2.1

web/app/scripts/workspace/workspace-drawing-board.html, web/app/scripts/workspace/workspace-wrapper.js, web/app/styles/workspace.css
Resolves #156. Just a slight glow. It's enough to help find these boxes. There's no animation. 😅
=> Highlight wizard boxes

app/com/lynxanalytics/sandbox/ScalaScript.scala
Other functions in this file that run code are already cached, but I guess this was not slow enough. But I now have a workspace where it would take a couple seconds to just open the parameters of a Derive box. This fixed it.
=> Cache surprisingly slow findVariables calls

tools/call_spark_submit.sh
=> Workaround for realpath bug in sbt-native-packager

CHANGELOG.md, docker/.dockerignore, docker/.gitignore, release.sh
I've also cut 4.3.0 at this point!
=> Release script

CHANGELOG.md, sphynx/python/install-dependencies.sh
Much easier! I'll have to check if it's compatible with our code. But I want to fix the build ASAP.
=> Upgrade to PyG 2.0.1

web/app/admin-manual/installation/kerberos.asciidoc
=> Add note about using Kerberos from Docker

app/com/lynxanalytics/biggraph/controllers/Project.scala
Sorry, this is not very meaningful for the open-source repo because it doesn't have user management. I'm just porting this for our convenience.
=> Clearer ACL semantics

CHANGELOG.md, conda-env.yml, docker/Dockerfile, sphynx/lynxkite-sphynx/networkit_community_detection.go, sphynx/python/node2vec.py, sphynx/python/util.py, test/com/lynxanalytics/biggraph/frontend_operations/NetworKitTest.scala, web/gulpfile.js, web/test/tests/instrument-test.js
Added a few missed items to CHANGELOG and dependencies. If tests pass, this will be it!
=> Very last changes for 4.4.0

conda-env.yml, tools/runtime-env.yml
Missed this in #234. Hopefully the last thing for 4.4.0...
=> Fix versions in runtime-env.yml

sphynx/networkit/build_env.sh
I'm embarrassed to say how much time I spent figuring out what was causing the compile errors in one of my local repos... 😅
=> Always use the right NetworKit includes

CHANGELOG.md, app/com/lynxanalytics/biggraph/spark_util/HybridRDD.scala, build.sbt, docker/Dockerfile, python/remote_api/tests/test_spark_conversion.py, release.sh, sphynx/dapcstp/README.md, sphynx/python/cugraph_connected_components.py, sphynx/python/cugraph_instead_of_networkit.py, sphynx/python/models.py, sphynx/python/util.py, tools/runtime-env-cuda.yml, tools/runtime-env.yml
=> Create 5.0.0 release

app/com/lynxanalytics/biggraph/frontend_operations/ImportOperations.scala, dependency-licenses/javascript.md, dependency-licenses/javascript.txt
=> Make Neo4j queries multiline

app/com/lynxanalytics/biggraph/frontend_operations/VertexAttributeOperations.scala, test/com/lynxanalytics/biggraph/frontend_operations/AddRankAttributeOperationTest.scala
=> Add ranking for edge attributes

test/com/lynxanalytics/biggraph/frontend_operations/AggregateEdgeAttributeGloballyOperationTest.scala, test/com/lynxanalytics/biggraph/frontend_operations/AggregateEdgeAttributeToVerticesOperationTest.scala, test/com/lynxanalytics/biggraph/frontend_operations/AggregateFromSegmentationOperationTest.scala, test/com/lynxanalytics/biggraph/frontend_operations/AggregateOnNeighborsTest.scala, test/com/lynxanalytics/biggraph/frontend_operations/AggregateToSegmentationOperationTest.scala, test/com/lynxanalytics/biggraph/frontend_operations/AggregateVertexAttributeGloballyOperationTest.scala
Not happy with the type conversion in AggregateFromSegmentationOperationTest.scala yet
=> [WIP] Add aggregation tests

app/com/lynxanalytics/biggraph/frontend_operations/AttributePropagationOperations.scala, test/com/lynxanalytics/biggraph/frontend_operations/AggregateOnNeighborsTest.scala
=> Allow edge attributes to be used as weight in 'weighted aggregate on neighbours'

web/app/styles/graph-view.css
=> Distinguish blue legend from the sea in geographic visualizations

docker/Dockerfile, sphynx/python/cugraph_connected_components.py, sphynx/python/cugraph_instead_of_networkit.py, sphynx/python/cugraph_pagerank.py
I'm pretty sure it worked last week. But cuGraph 22.08 was released 21 days ago so maybe I'm wrong. But it works with this!
=> Fixes for new cuGraph

tools/runtime-env-gen.sh
I used this in #272 but forgot to `git add` it.
=> Script for generating runtime environment configs

app/com/lynxanalytics/biggraph/BigGraphEnvironment.scala
Probably not a common issue, but I messed up my settings and got a weird error message.
=> Better error message for weird KITE_DOMAINS settings

CHANGELOG.md
Release looks all good so far! I've pushed the images to Docker Hub.
=> Cut 5.1.0 in changelog

app/com/lynxanalytics/biggraph/graph_api/JsonSerialization.scala, app/com/lynxanalytics/biggraph/graph_api/KeyValueStore.scala, app/com/lynxanalytics/biggraph/graph_api/MetaGraph.scala, app/com/lynxanalytics/biggraph/graph_operations/ImportDataFrame.scala, app/com/lynxanalytics/biggraph/graph_operations/MetaGraph.scala, app/com/lynxanalytics/biggraph/graph_util/HadoopFile.scala, app/com/lynxanalytics/biggraph/graph_util/SoftHashMap.scala, test/com/lynxanalytics/biggraph/graph_api/MetaGraphManagerTest.scala
Resolves #260. To up the stakes, I've also added some code changes. 😈 
Any other dark areas I should try to illuminate?
=> Comments for a few tricky places

web/tests/dummy-param.spec.ts, web/tests/example-graph.spec.ts, web/tests/lynxkite.ts
Part of #238 solution. See also #307
=> Rewrite example graph test

web/tests/choice-params-with-default.spec.ts, web/tests/lynxkite.ts
=> Finish converting the choice-params tests

tools/with_lk.sh, web/playwright.config.ts, web/tests/drag-select.spec.ts, web/tests/lynxkite.ts
Do I need to rewrite selectArea()?
=> Rewrite drag selection test

web/tests/choice-params-with-default.spec.ts, web/tests/copy-paste.spec.ts, web/tests/custom-box.spec.ts, web/tests/data/upload_test.csv, web/tests/delete-test.spec.ts, web/tests/drag-select.spec.ts, web/tests/dummy-param.spec.ts, web/tests/example-graph.spec.ts, web/tests/filter.spec.ts, web/tests/fork-workspace.spec.ts, web/tests/histogram.spec.ts, web/tests/lynxkite.ts, web/tests/metaeditor.spec.ts, web/tests/plot.spec.ts, web/tests/splash.spec.ts, web/tests/sql.spec.ts, web/tests/upload.spec.ts
=> Convert upload test

web/tests/lynxkite.ts, web/tests/unexpected-params.spec.ts
For #238. A straight conversion. I barely thought about what this does, I'm just glad it passes.
=> Convert unexpected-params.js

web/tests/example-graph.spec.ts, web/tests/lynxkite.ts, web/tests/operations.spec.ts
For #238. These were both commented out. I salvaged what I could, but it's still a pretty lightweight test. Maybe we can add more later.
=> Convert operations-test.js and sort-listed-attributes-test.js

web/tests/lynxkite.ts, web/tests/segmentation.spec.ts
For #238.
Another straightforward conversion. I'm also cleaning up some stuff in `lynxkite.ts`. Eventually it will have to not look like a pile of garbage!
=> Convert segmentation-test.js

.github/workflows/earthly-test.yml, Earthfile
I think this works, but let's see on GitHub Actions.
=> Another way to save the report for a failed test

web/tests/operation-selector.spec.ts
=> Migrate operation-selector-test.js to Playwright

Earthfile, dependency-licenses/javascript.md, dependency-licenses/javascript.txt, web/app/scripts/project/model-details.html, web/tests/lynxkite.ts, web/tests/model.spec.ts, web/tests/segmentation.spec.ts
For #238. I switched from a CSV import to a Python box to make the test more self-contained.
=> Convert model-test.js to Playwright

app/com/lynxanalytics/biggraph/controllers/Workspace.scala, app/com/lynxanalytics/biggraph/graph_api/MetaGraphManager.scala
=> Fix a deadlock

CHANGELOG.md, app/com/lynxanalytics/biggraph/controllers/Operation.scala, dependency-licenses/scala.md, web/app/help/workspace-ui/custom-boxes.asciidoc, web/app/scripts/operation/operation-parameters.html, web/app/scripts/operation/parameters-parameter.html, web/app/scripts/operation/parameters-parameter.js, web/app/scripts/workspace/box-editor.js, web/tests/custom-box.spec.ts, web/tests/lynxkite.ts
When I said this was a lot of work, I didn't anticipate that I would just abuse the default value setting for this. :blush: 
We could make a more complex solution with a dedicated box on the UI for specifying the choices. But it doesn't sound like a good deal, even from a user's perspective. Simple is better.
I would love to add a test, but the workspace parameters are pretty broken at the moment. (#370) Let's fix that and add a test for this at the same time.
=> Dropdown parameter for custom boxes

conda-env.yml, docker/Dockerfile, sphynx/python/derive.py, sphynx/python/llm_pandas_on_graph.py, sphynx/python/util.py, web/app/help/operations/compute-in-python.asciidoc, web/app/scripts/util/util.js
I didn't test without examples. :sob:
I'll also do something about #382, #383 and #384. Give me a sec!
=> Fix OpenAI box for missing inputs/outputs

CHANGELOG.md
It's not a user-visible change, so it doesn't really matter. But if we're mentioning Vite, we should mention Playwright too.
=> Cut 5.3.0 in changelog

sphynx/python/llm_pandas_on_graph.py
I added this a few days ago when debugging something. It's useful!
=> Log exceptions in generated code

CHANGELOG.md
It's a very small release with just two changes.
=> Mark 5.3.1 in the changelog

resources/built-ins/ask-OpenAI
OpenAI box does not work in e.g. Databricks environment.
=> Comply with java < 11

CHANGELOG.md, python_requirements_testing.txt, release.sh
Almost entirely a packaging change, but still I think it's clearer to give it a separate number.
=> Release 5.4.1
